---
serviceAccount:
  create: true
  name: ""
  annotations: {}
  labels: {}
  imagePullSecrets: []
command: []
args: []
extraEnv: |
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: {{ db_host }}
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: {{ db_name }}
  - name: KC_PROXY
    value: edge
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "true"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
extraEnvFrom: |
  - secretRef:
      name: 'keycloak-creds'
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
secrets:
  creds:
    stringData:
      DB_USER: "{{ db_name }}"
      DB_PASSWORD: "{{ db_password }}"
      KEYCLOAK_USER: "{{ keycloak_admin_username }}"
      KEYCLOAK_PASSWORD: "{{ keycloak_admin_password }}"
service:
  annotations: {}
  labels: {}
  type: ClusterIP
  httpPort: 80
  httpNodePort: null
  httpsPort: 8443
  httpsNodePort: null
  httpManagementPort: 9990
  httpManagementNodePort: null
  extraPorts: []
ingress:
  enabled: true
  ingressClassName: "nginx"
  servicePort: http
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels: {}
  rules:
    - host: 'keycloak.k8s.samerbahri.tk'
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "*.k8s.samerbahri.tk"
      secretName: wildcard-k8s-samerbahri-tk-tls
  console:
    enabled: true
    # The name of Ingress Class associated with the console ingress only
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rules:
      - host: 'keycloak.k8s.samerbahri.tk'
        paths:
          - path: /auth/admin/
            pathType: Prefix
    tls:
      - hosts:
          - "*.k8s.samerbahri.tk"
        secretName: wildcard-k8s-samerbahri-tk-tls
postgresql:
  enabled: false
