---
- name: KEYCLOAK | ENSURE ABSENT
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    - app/keycloak
    - resource/mysql/db
  vars:
    state: absent
    db_name: keycloak
    db_host:
      "{{ lookup('viczem.keepass.keepass','MySQL/ROOT','url') }}"
    db_password:
      "{{ lookup('viczem.keepass.keepass','MySQL/Keycloak','password') }}"
