---
- name: MySQL | ENSURE PRESENT
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    - resource/postgres/db
    - app/keycloak
  vars:
    state: present
    namespace: adminer
    db_name: keycloak
    db_host:
      "{{ lookup('viczem.keepass.keepass','Postgres/ROOT','url') }}"
    db_password:
      "{{ lookup('viczem.keepass.keepass','Postgres/Keycloak','password') }}"
