---
- name: MySQL | ENSURE PRESENT
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    - resource/postgres/db
  vars:
    state: present
    db_name: keycloak
    db_host:
      "{{ lookup('viczem.keepass.keepass','POSTGRES/ROOT','url') }}"
    db_password:
      "{{ lookup('viczem.keepass.keepass','POSTGRES/Keycloak','password') }}"
