---
- name: KEYCLOAK | ENSURE PRESENT
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    - resource/mysql/db
    - app/keycloak
  vars:
    state: present
    namespace: adminer
    db_name: keycloak
    db_host:
      "{{ lookup('viczem.keepass.keepass','MySQL/ROOT','url') }}"
    db_password:
      "{{ lookup('viczem.keepass.keepass','MySQL/Keycloak','password') }}"
    hostname: "keycloak.mm.samerbahri.tk"
    cert_hostname: "*.mm.samerbahri.tk"
    cert_secret: "wildcard-mm-samerbahri-tk-tls"
