---
- name: HELM REPOSITORY | IMPORT BITNAMI
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
- name: KEYCLOAK | STATE
  import_tasks: "{{ state }}.yml"
  vars:
    keycloak_admin_username:
      "{{ lookup('viczem.keepass.keepass','Keycloak/ROOT','username') }}"
    keycloak_admin_password:
      "{{ lookup('viczem.keepass.keepass','Keycloak/ROOT','password') }}"
