---
- name: ZUUL | ENSURE PRESENT
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    - app/zuul
  vars:
    state: absent
    namespace: zuul
    db_name: zuul
    db_host:
      "{{ lookup('viczem.keepass.keepass','MySQL/ROOT','url') }}"
    db_password:
      "{{ lookup('viczem.keepass.keepass','MySQL/Zuul','password') }}"
