---
- name: install jenkins
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    - app/jenkins
  vars:
    state: present
    namespace: adminer
    db_host: pxc-db-haproxy.percona.svc.cluster.local
