---
- name: install jenkins
  hosts: localhost
  become: false
  gather_facts: false
  roles:
    - app/jenkins
  vars:
    state: present
    hostname: "jenkins.mm.samerbahri.tk"
    cert_hostname: "*.mm.samerbahri.tk"
    cert_secret: "wildcard-mm-samerbahri-tk-tls"
