---
- name: ZUUL | CRD
  kubernetes.core.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    template: crd.yaml
  when:
    - state == "present"
- name: ZUUL | RBAC
  kubernetes.core.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    template: rbac.yaml
  when:
    - state == "present"
- name: ZUUL | OPERATOR
  kubernetes.core.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    template: operator.yaml
- name: ZUUL | RBAC
  kubernetes.core.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    template: rbac.yaml
  when:
    - state == "absent"
- name: ZUUL | CRD
  kubernetes.core.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    template: crd.yaml
  when:
    - state == "absent"
