---
- name: SSH | KEY PAIRS
  community.crypto.openssh_keypair:
    regenerate: "never"
    path:
      "{{ lookup('viczem.keepass.keepass',
      'Jenkins/GitHub-PAT','attachments', 'id_rsa_jenkins') }}"
  register: openssh_keys
- name: Read kube server address
  command: kubectl config view -o jsonpath='{.clusters[0].cluster.server}'
  register: _kube_config
  when:
    - state == "present"
- name: Read generated kubectl configuration
  shell:
    "set -o pipefail && kubectl config view --flatten |
     sed -e 's#{{ _kube_config.stdout }}#https://kubernetes/#g'"
  register: _kube_config
  when:
    - state == "present"
- name: Read current context name
  command: kubectl config current-context
  register: _kube_context
  when:
    - state == "present"
- name: ZUUL | STATIC NODE SECRET
  kubernetes.core.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: static-node-authorized-keys
      data:
        authorized_keys: "{{ openssh_keys.public_key | b64encode }}"
- name: ZUUL | SECRETS
  kubernetes.core.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
      stringData: "{{ item.data }}"
  loop: "{{ secrets }}"
