---
- name: HELM | INSTALL JENKINS
  kubernetes.core.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    chart_version: 4.2.3
    release_namespace: "{{ namespace }}"
    create_namespace: true
    values: "{{ lookup('template','jenkins.values.yml') | from_yaml }}"
