---
apiVersion: operator.zuul-ci.org/v1alpha2
kind: Zuul
metadata:
  name: zuul
  namespace: "{{ namespace }}"
spec:
  database:
    secretName: pxc
  executor:
    count: 1
    sshkey:
      secretName: github-secrets
  merger:
    count: 1
  scheduler:
    config:
      secretName: zuul-yaml-conf
  launcher:
    config:
      secretName: nodepool-yaml-conf
  connections:
    github:
      driver: github
      secretName: github-secrets
      rate_limit_logging: true
  externalConfig:
    kubernetes:
      secretName: nodepool-kube-config
  registry:
    count: 0
  preview:
    count: 1
  web:
    count: 1
