---
nameOverride: ""
fullnameOverride: ""

finalizers:
  - delete-mysql-pods-in-order

crVersion: 0.3.0
pause: false
allowUnsafeConfigurations: false

mysql:
  clusterType: async
  image:
    repository: percona/percona-server
    tag: 8.0.29
  imagePullPolicy: Always
  imagePullSecrets: []
  size: 3
  sizeSemiSync: 0

  resources:
    requests:
      cpu: 50m
      memory: 128M
    limits:
      cpu: 500m
      memory: 256M

  affinity:
    antiAffinityTopologyKey: "kubernetes.io/hostname"

  expose:
    enabled: false
    type: ClusterIP

  volumeSpec:
    pvc:
      resources:
        requests:
          storage: 1G
  annotations: {}
  labels: {}
  nodeSelector: {}
  tolerations: []

haproxy:
  enabled: false

router:
  image:
    repository: percona/percona-server-mysql-operator
    tag: 0.3.0-router
  imagePullPolicy: Always
  imagePullSecrets: []

  size: 1

  resources:
    requests:
      memory: 256M
    limits:
      memory: 256M

  affinity:
    antiAffinityTopologyKey: "kubernetes.io/hostname"

  annotations: {}
  labels: {}
  nodeSelector: {}
  tolerations: []


orchestrator:
  image:
    repository: percona/percona-server-mysql-operator
    tag: 0.3.0-orchestrator
  imagePullPolicy: Always
  imagePullSecrets: []

  size: 1

  resources:
    requests:
      memory: 128M
    limits:
      memory: 256M

  affinity:
    antiAffinityTopologyKey: "kubernetes.io/hostname"

  volumeSpec:
    pvc:
      resources:
        requests:
          storage: 1G

pmm:
  enabled: false

backup:
  enabled: false

toolkit:
  image:
    repository: percona/percona-server-mysql-operator
    tag: 0.3.0-toolkit
  imagePullPolicy: Always
  resources:
    requests: {}
    limits: {}

secrets:
  passwords:
    root:
      "{{ lookup('viczem.keepass.keepass', 'MySQL/ROOT', 'password') }}"
    xtrabackup:
      "{{ lookup('viczem.keepass.keepass', 'MySQL/ROOT', 'password') }}"
    monitor:
      "{{ lookup('viczem.keepass.keepass', 'MySQL/ROOT', 'password') }}"
    pmmserverkey:
      "{{ lookup('viczem.keepass.keepass', 'MySQL/ROOT', 'password') }}"
    operator:
      "{{ lookup('viczem.keepass.keepass', 'MySQL/ROOT', 'password') }}"
    replication:
      "{{ lookup('viczem.keepass.keepass', 'MySQL/ROOT', 'password') }}"
    orchestrator:
      "{{ lookup('viczem.keepass.keepass', 'MySQL/ROOT', 'password') }}"
    heartbeat:
      "{{ lookup('viczem.keepass.keepass', 'MySQL/ROOT', 'password') }}"
