---
- name: DOWNLOAD | HELM
  ansible.builtin.get_url:
    url:
      "https://get.helm.sh/helm-v3.10.0-linux-amd64.tar.gz"
    dest: /tmp/helm.tar.gz
    owner: root
    group: root
    mode: 0755

- name: UNTAR | HELM
  ansible.builtin.unarchive:
    src: /tmp/helm.tar.gz
    remote_src: true
    dest: /tmp
    owner: root
    group: root
    mode: 0755

- name: INSTALL | HELM
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755

- name: DELETE | HELM INSTALLATION
  ansible.builtin.file:
    path: /tmp/helm.tar.gz
    state: absent
