---
- name: DOWNLOAD | KUBECTL
  ansible.builtin.get_url:
    url:
      "https://dl.k8s.io/release/v1.25.2\
      /bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755

- name: HELM
  import_tasks: helm.yml

- name: K9S
  import_tasks: k9s.yml
