---
- name: DOWNLOAD | KUBECTL
  ansible.builtin.get_url:
    url:
      "https://dl.k8s.io/release/v1.25.2\
      /bin/linux/amd64/kubectl"
    checksum: |
      sha256:9cc2d6ce59740b6acf6d5d4a04d4a7d839b0a81373248ef0ce6c8d707143435b
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755

- name: HELM
  import_tasks: helm.yml

- name: K9S
  import_tasks: k9s.yml
