---
- name: HELM REPOSITORY | IMPORT CERT-MANAGER
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
- name: HELM REPOSITORY | IMPORT VULTR-WEBHOOK
  kubernetes.core.helm_repository:
    name: vultr
    repo_url: https://vultr.github.io/helm-charts/
- name: CERT-MANAGER | STATE
  import_tasks: "{{ state }}.yml"
