---
name: deploy-k8s-cluster

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy kubernetes cluster
    env:
      AWS_PAGER: ''
      AWS_ACCESS_KEY_ID: '${{ secrets.BACKBLAZE_ACCESS_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.BACKBLAZE_ACCESS_KEY }}'
      AWS_REGION: us-west-1
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.3
      - name: get terraform lock
        run:
          "aws s3api get-object
          --bucket samerbahri98-k8s-admin-terraform-state
          --key .terraform.lock.hcl
          --endpoint https://s3.us-west-004.backblazeb2.com
          --no-cli-pager
          .terraform.lock.hcl"
        working-directory: ./terraform
      - name: get terraform tfvars
        run:
          "aws s3api get-object
          --bucket samerbahri98-k8s-admin-terraform-state
          --key terraform.tfvars
          --endpoint https://s3.us-west-004.backblazeb2.com
          --no-cli-pager
          terraform.tfvars"
        working-directory: ./terraform
      - run: terraform init --upgrade
        working-directory: ./terraform
      - run: terraform plan
        working-directory: ./terraform
      - run: terraform apply --auto-approve
        working-directory: ./terraform
        continue-on-error: true
      - name: update terraform lock
        run:
          "aws s3api put-object
          --bucket samerbahri98-k8s-admin-terraform-state
          --key .terraform.lock.hcl
          --endpoint https://s3.us-west-004.backblazeb2.com
          --body $PWD/.terraform.lock.hcl"
        working-directory: ./terraform
      - name: cleanup
        run: rm -rf .terraform.lock.hcl terraform.tfvars
        working-directory: ./terraform
