---
name: zuul-static-node-build

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DOCKERFILE_DIR: roles/app/zuul/files
jobs:
  build:
    runs-on: ubuntu-latest
    name: build docker image
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: lint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ${{ env.DOCKERFILE_DIR }}/static-node.Dockerfile
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-zst
      - uses: docker/build-push-action@v3
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ env.DOCKERFILE_DIR }}/static-node.Dockerfile
